steps:

- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker pull gcr.io/$PROJECT_ID/todo-apps:latest || exit 0'
  ]

- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/$PROJECT_ID/todo-apps:$TAG_NAME',
   '-t', 
   'gcr.io/$PROJECT_ID/todo-apps:latest',
   '.'
  ]

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster-demo'

- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'todo-apps-deployment', 
   'todo-apps=gcr.io/$PROJECT_ID/todo-apps:$TAG_NAME'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster-demo'
  
# push images to GCR
images: [
   'gcr.io/$PROJECT_ID/todo-apps:$TAG_NAME',
   'gcr.io/$PROJECT_ID/todo-apps:latest'
  ]