steps:

- id: Download cache artifact
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
          docker pull gcr.io/$PROJECT_ID/todo-apps:latest || exit 0

- id: Build Docker image with cache
  name: 'gcr.io/cloud-builders/docker'
  args: [
           'build',
           '-t', 'gcr.io/$PROJECT_ID/todo-apps:latest',
           '--cache-from', 'gcr.io/$PROJECT_ID/todo-apps:latest',
           '.'
        ]
 
- id: Push image to GCR
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/todo-apps']


# Deploy
- id: Deploy to k8s Cluster
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster-demo'

# Rolling Update Image
- id: Rolling Updat Container Image
  name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'todo-apps-deployment', 
   'todo-apps=gcr.io/$PROJECT_ID/todo-apps:latest'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster-demo'
  