apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todo-apps-deployment
spec:
  selector:
    matchLabels:
      app: todo-apps
  replicas: 2
  template:
    metadata:
      labels:
        app: todo-apps
        env: development
    spec:
      containers:
      - name: todo-apps
        image: gcr.io/narasi-infrastructure/todo-apps:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"

