apiVersion: v1
kind: Service
metadata:
  name: apps-service
  labels:
    app: todo-apps-deployment
spec:
  selector:
    app: todo-apps
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: "35.232.198.116"
